data_ingestion:
  test_size: 0.30

model_training:
  models:
    KNN:
      n_neighbors: [1, 5, 10, 15, 20,25,30]
    Ridge:
      alpha: [1,5, 10]
    Lasso:
      alpha: [1,5, 10]
    RandomForest:
      n_estimators: [20,50, 100]
      max_depth: [10, 20,30]
      min_samples_split: [2, 5,10]
      min_samples_leaf: [1, 2,5]
    XGBoost:
      learning_rate: [0.01, 0.1,1]
      max_depth: [2,3, 5]
      min_child_weight: [1,2, 3]
      subsample: [0.7, 1,1.3]
      n_estimators: [50,100, 200]
